spring:
  profiles.active: default

---
spring:
  profiles: default
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF8&autoReconnect=true
  username: root
  password: home
spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    ddl-auto: none
  show-sql: true
---
spring:
  profiles: production
---

  # JACKSON
  spring:
    jackson:
      serialization:
        INDENT_OUTPUT: true

  jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    route:
      authentication:
        path: auth
        refresh: refresh

#logging:
    level:
      org.springframework:
        security: DEBUG